# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d97e997ed1bdac0bcad182c9acf89a29f28868216bd0c4014909eedc7adb75efc97cf7b4f1944595ec6db75d12f747b39f2add98a6763edf6803c5a331f0a97

test:
  secret_key_base: cd4072dcd5defdc260ce9236b0e7c1ce7df9045c69ebc1d91ba39b0e8a04b8aa35b7f46ad935ef5c8c12918a2e81c2b8041b162de73e484646f6d29bee123aad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
